Fix ambiguity for "=" operator involving String and Unbounded_String
The usage of the "=" operator with an overloaded left operand with String
and Unbounded_String interpretations and a String right operand is illegal
because it is ambiguous.  This will be diagnosed by an enhanced compiler:

gps-kernel-remote.adb:215:44:
  error: ambiguous expression (cannot resolve "=")
gps-kernel-remote.adb:215:44:
  error: possible interpretation at a-strunb.ads:248
gps-kernel-remote.adb:215:44:
  error: possible interpretation in package Standard

TN: V112-041
Change-Id: I1167341e25288db767c6050c5a2a9b601cb85192
(cherry picked from commit d6332c80de9c1dec8b2a6fc0c053cab775b4e4c7)
(cherry picked from commit d458073e69ac12ba4eab3e08450506cf7f12877c)