Fix gps_library compilation error
gps-kernel-shared_macros.adb:208:26: "GNAT" is not visible
gps-kernel-shared_macros.adb:208:26: non-visible declaration at gnat.ads:34
gps-kernel-shared_macros.adb:208:26: missing "with GNAT;"


git-svn-id: svn+ssh://svn.eu.adacore.com/Dev/trunk/gps@187342 936e1b1b-40f2-da11-902a-00137254ae57